# ansible setup
ansible_ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# sudo user
ssh_user: ansible
ssh_groups: "sudo"

# Wordpress Database setup
host_name: "142.93.214.145"
wp_db_name: wordpress1
wp_db_user: wordpress
wp_db_password: w0rdpr355
wp_db_prefix: wp_

# Wp website setup
wp_title: Demo Beta Website
wp_admin_user: admin
wp_admin_password: admin450
wp_admin_email: admin@example.com
